/*
 * Copyright 2025 Sawyerlsy
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/******************************************/
/*   数据库全名 = nacos_config   */
/*   表名称 = config_info   */
/******************************************/
CREATE TABLE config_info (
                             id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
                             data_id VARCHAR(255) NOT NULL,
                             group_id VARCHAR(128),
                             content TEXT NOT NULL,
                             md5 VARCHAR(32),
                             gmt_create TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
                             gmt_modified TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
                             src_user TEXT,
                             src_ip VARCHAR(50),
                             app_name VARCHAR(128),
                             tenant_id VARCHAR(128) DEFAULT '',
                             c_desc VARCHAR(256),
                             c_use VARCHAR(64),
                             effect VARCHAR(64),
                             type VARCHAR(64),
                             c_schema TEXT,
                             encrypted_data_key TEXT,
                             PRIMARY KEY (id)
);
COMMENT ON TABLE config_info IS 'config_info';
CREATE UNIQUE INDEX uk_configinfo_datagrouptenant ON config_info(data_id, group_id, tenant_id);

/******************************************/
/*   数据库全名 = nacos_config   */
/*   表名称 = config_info_aggr   */
/******************************************/
CREATE TABLE config_info_aggr (
                                  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                  data_id VARCHAR(255) NOT NULL,
                                  group_id VARCHAR(128) NOT NULL,
                                  datum_id VARCHAR(255) NOT NULL,
                                  content TEXT NOT NULL,
                                  gmt_modified TIMESTAMP(6) NOT NULL,
                                  app_name VARCHAR(128),
                                  tenant_id VARCHAR(128) DEFAULT '',
                                  PRIMARY KEY (id)
);
COMMENT ON TABLE config_info_aggr IS '增加租户字段';
CREATE UNIQUE INDEX uk_configinfoaggr_datagrouptenantdatum ON config_info_aggr(data_id, group_id, tenant_id, datum_id);

/******************************************/
/*   数据库全名 = nacos_config   */
/*   表名称 = config_info_beta   */
/******************************************/
CREATE TABLE config_info_beta (
                                  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                  data_id VARCHAR(255) NOT NULL,
                                  group_id VARCHAR(128) NOT NULL,
                                  app_name VARCHAR(128),
                                  content TEXT NOT NULL,
                                  beta_ips VARCHAR(1024),
                                  md5 VARCHAR(32),
                                  gmt_create TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
                                  gmt_modified TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
                                  src_user TEXT,
                                  src_ip VARCHAR(50),
                                  tenant_id VARCHAR(128) DEFAULT '',
                                  encrypted_data_key TEXT,
                                  PRIMARY KEY (id)
);
COMMENT ON TABLE config_info_beta IS 'config_info_beta';
CREATE UNIQUE INDEX uk_configinfobeta_datagrouptenant ON config_info_beta(data_id, group_id, tenant_id);

/******************************************/
/*   数据库全名 = nacos_config   */
/*   表名称 = config_info_tag   */
/******************************************/
CREATE TABLE config_info_tag (
                                 id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                 data_id VARCHAR(255) NOT NULL,
                                 group_id VARCHAR(128) NOT NULL,
                                 tenant_id VARCHAR(128) DEFAULT '',
                                 tag_id VARCHAR(128) NOT NULL,
                                 app_name VARCHAR(128),
                                 content TEXT NOT NULL,
                                 md5 VARCHAR(32),
                                 gmt_create TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
                                 gmt_modified TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
                                 src_user TEXT,
                                 src_ip VARCHAR(50),
                                 PRIMARY KEY (id)
);
COMMENT ON TABLE config_info_tag IS 'config_info_tag';
CREATE UNIQUE INDEX uk_configinfotag_datagrouptenanttag ON config_info_tag(data_id, group_id, tenant_id, tag_id);

/******************************************/
/*   数据库全名 = nacos_config   */
/*   表名称 = config_tags_relation   */
/******************************************/
CREATE TABLE config_tags_relation (
                                      id BIGINT NOT NULL,
                                      tag_name VARCHAR(128) NOT NULL,
                                      tag_type VARCHAR(64),
                                      data_id VARCHAR(255) NOT NULL,
                                      group_id VARCHAR(128) NOT NULL,
                                      tenant_id VARCHAR(128) DEFAULT '',
                                      nid BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                      PRIMARY KEY (nid)
);
COMMENT ON TABLE config_tags_relation IS 'config_tag_relation';
CREATE UNIQUE INDEX uk_configtagrelation_configidtag ON config_tags_relation(id, tag_name, tag_type);
CREATE INDEX idx_configtagrelation_tenant_id ON config_tags_relation(tenant_id);

/******************************************/
/*   数据库全名 = nacos_config   */
/*   表名称 = group_capacity   */
/******************************************/
CREATE TABLE group_capacity (
                                id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                group_id VARCHAR(128) NOT NULL DEFAULT '',
                                quota INT NOT NULL DEFAULT 0,
                                usage INT NOT NULL DEFAULT 0,
                                max_size INT NOT NULL DEFAULT 0,
                                max_aggr_count INT NOT NULL DEFAULT 0,
                                max_aggr_size INT NOT NULL DEFAULT 0,
                                max_history_count INT NOT NULL DEFAULT 0,
                                gmt_create TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
                                gmt_modified TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
                                PRIMARY KEY (id)
);
COMMENT ON TABLE group_capacity IS '集群、各Group容量信息表';
CREATE UNIQUE INDEX uk_group_id ON group_capacity(group_id);

/******************************************/
/*   数据库全名 = nacos_config   */
/*   表名称 = his_config_info   */
/******************************************/
CREATE TABLE his_config_info (
                                 id BIGINT NOT NULL,
                                 nid BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                 data_id VARCHAR(255) NOT NULL,
                                 group_id VARCHAR(128) NOT NULL,
                                 app_name VARCHAR(128),
                                 content TEXT NOT NULL,
                                 md5 VARCHAR(32),
                                 gmt_create TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
                                 gmt_modified TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
                                 src_user TEXT,
                                 src_ip VARCHAR(50),
                                 op_type CHAR(10),
                                 tenant_id VARCHAR(128) DEFAULT '',
                                 encrypted_data_key TEXT,
                                 PRIMARY KEY (nid)
);
COMMENT ON TABLE his_config_info IS '多租户改造';
CREATE INDEX idx_gmt_create ON his_config_info(gmt_create);
CREATE INDEX idx_gmt_modified ON his_config_info(gmt_modified);
CREATE INDEX idx_did ON his_config_info(data_id);

/******************************************/
/*   数据库全名 = nacos_config   */
/*   表名称 = tenant_capacity   */
/******************************************/
CREATE TABLE tenant_capacity (
                                 id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                 tenant_id VARCHAR(128) NOT NULL DEFAULT '',
                                 quota INT NOT NULL DEFAULT 0,
                                 usage INT NOT NULL DEFAULT 0,
                                 max_size INT NOT NULL DEFAULT 0,
                                 max_aggr_count INT NOT NULL DEFAULT 0,
                                 max_aggr_size INT NOT NULL DEFAULT 0,
                                 max_history_count INT NOT NULL DEFAULT 0,
                                 gmt_create TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
                                 gmt_modified TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
                                 PRIMARY KEY (id)
);
COMMENT ON TABLE tenant_capacity IS '租户容量信息表';
CREATE UNIQUE INDEX uk_tenant_id ON tenant_capacity(tenant_id);

/******************************************/
/*   表名称 = tenant_info   */
/******************************************/
CREATE TABLE tenant_info (
                             id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                             kp VARCHAR(128) NOT NULL,
                             tenant_id VARCHAR(128) DEFAULT '',
                             tenant_name VARCHAR(128) DEFAULT '',
                             tenant_desc VARCHAR(256),
                             create_source VARCHAR(32),
                             gmt_create BIGINT NOT NULL,
                             gmt_modified BIGINT NOT NULL,
                             PRIMARY KEY (id)
);
COMMENT ON TABLE tenant_info IS 'tenant_info';
CREATE UNIQUE INDEX uk_tenant_info_kptenantid ON tenant_info(kp, tenant_id);
CREATE INDEX idx_tenant_info_tenant_id ON tenant_info(tenant_id);

/******************************************/
/*   权限系统表   */
/******************************************/
CREATE TABLE users (
                       username VARCHAR(50) PRIMARY KEY,
                       password VARCHAR(500) NOT NULL,
                       enabled BOOLEAN NOT NULL
);

CREATE TABLE roles (
                       username VARCHAR(50) NOT NULL,
                       role VARCHAR(50) NOT NULL,
                       UNIQUE (username, role)
);

CREATE TABLE permissions (
                             role VARCHAR(50) NOT NULL,
                             resource VARCHAR(255) NOT NULL,
                             action VARCHAR(8) NOT NULL,
                             UNIQUE (role, resource, action)
);

-- 初始化数据
INSERT INTO users (username, password, enabled) VALUES
    ('nacos', '$2a$10$EuWPZHzz32dJN7jexM34MOeYirDdFAZm2kuWj7VEOJhhZkDrxfvUu', TRUE);
INSERT INTO roles (username, role) VALUES ('nacos', 'ROLE_ADMIN');

---------------------------- 优化配置 ----------------------------
-- 设置存储参数（基于网页7性能建议）
ALTER TABLE config_info SET (FILLFACTOR=90, PARALLEL_WORKERS=4);
ALTER TABLE his_config_info SET (FILLFACTOR=85, PARALLEL_WORKERS=4);
